complete -c volta -n "__fish_use_subcommand" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_use_subcommand" -l quiet -d 'Prevents unnecessary output'
complete -c volta -n "__fish_use_subcommand" -s v -l version -d 'Prints the current version of Volta'
complete -c volta -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_use_subcommand" -f -a "fetch" -d 'Fetches a tool to the local machine'
complete -c volta -n "__fish_use_subcommand" -f -a "install" -d 'Installs a tool in your toolchain'
complete -c volta -n "__fish_use_subcommand" -f -a "uninstall" -d 'Uninstalls a tool from your toolchain'
complete -c volta -n "__fish_use_subcommand" -f -a "pin" -d 'Pins your project\'s runtime or package manager'
complete -c volta -n "__fish_use_subcommand" -f -a "list" -d 'Displays the current toolchain'
complete -c volta -n "__fish_use_subcommand" -f -a "completions" -d 'Generates Volta completions'
complete -c volta -n "__fish_use_subcommand" -f -a "which" -d 'Locates the actual binary that will be called by Volta'
complete -c volta -n "__fish_use_subcommand" -f -a "use"
complete -c volta -n "__fish_use_subcommand" -f -a "setup" -d 'Enables Volta for the current user / shell'
complete -c volta -n "__fish_use_subcommand" -f -a "run" -d 'Run a command with custom Node, npm, and/or Yarn versions'
complete -c volta -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c volta -n "__fish_seen_subcommand_from fetch" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_seen_subcommand_from fetch" -s V -l version -d 'Prints version information'
complete -c volta -n "__fish_seen_subcommand_from fetch" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_seen_subcommand_from fetch" -l quiet -d 'Prevents unnecessary output'
complete -c volta -n "__fish_seen_subcommand_from install" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_seen_subcommand_from install" -s V -l version -d 'Prints version information'
complete -c volta -n "__fish_seen_subcommand_from install" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_seen_subcommand_from install" -l quiet -d 'Prevents unnecessary output'
complete -c volta -n "__fish_seen_subcommand_from uninstall" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_seen_subcommand_from uninstall" -s V -l version -d 'Prints version information'
complete -c volta -n "__fish_seen_subcommand_from uninstall" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_seen_subcommand_from uninstall" -l quiet -d 'Prevents unnecessary output'
complete -c volta -n "__fish_seen_subcommand_from pin" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_seen_subcommand_from pin" -s V -l version -d 'Prints version information'
complete -c volta -n "__fish_seen_subcommand_from pin" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_seen_subcommand_from pin" -l quiet -d 'Prevents unnecessary output'
complete -c volta -n "__fish_seen_subcommand_from list" -l format -d 'Specify the output format' -r -f -a "human plain"
complete -c volta -n "__fish_seen_subcommand_from list" -s c -l current -d 'Show the currently-active tool(s)'
complete -c volta -n "__fish_seen_subcommand_from list" -s d -l default -d 'Show your default tool(s).'
complete -c volta -n "__fish_seen_subcommand_from list" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_seen_subcommand_from list" -s V -l version -d 'Prints version information'
complete -c volta -n "__fish_seen_subcommand_from list" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_seen_subcommand_from list" -l quiet -d 'Prevents unnecessary output'
complete -c volta -n "__fish_seen_subcommand_from completions" -s o -l output -d 'File to write generated completions to'
complete -c volta -n "__fish_seen_subcommand_from completions" -s f -l force -d 'Write over an existing file, if any.'
complete -c volta -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c volta -n "__fish_seen_subcommand_from completions" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_seen_subcommand_from completions" -l quiet -d 'Prevents unnecessary output'
complete -c volta -n "__fish_seen_subcommand_from which" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_seen_subcommand_from which" -s V -l version -d 'Prints version information'
complete -c volta -n "__fish_seen_subcommand_from which" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_seen_subcommand_from which" -l quiet -d 'Prevents unnecessary output'
complete -c volta -n "__fish_seen_subcommand_from use" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_seen_subcommand_from use" -s V -l version -d 'Prints version information'
complete -c volta -n "__fish_seen_subcommand_from use" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_seen_subcommand_from use" -l quiet -d 'Prevents unnecessary output'
complete -c volta -n "__fish_seen_subcommand_from setup" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_seen_subcommand_from setup" -s V -l version -d 'Prints version information'
complete -c volta -n "__fish_seen_subcommand_from setup" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_seen_subcommand_from setup" -l quiet -d 'Prevents unnecessary output'
complete -c volta -n "__fish_seen_subcommand_from run" -l node -d 'Set the custom Node version'
complete -c volta -n "__fish_seen_subcommand_from run" -l npm -d 'Set the custom npm version'
complete -c volta -n "__fish_seen_subcommand_from run" -l yarn -d 'Set the custom Yarn version'
complete -c volta -n "__fish_seen_subcommand_from run" -l env -d 'Set an environment variable (can be used multiple times)'
complete -c volta -n "__fish_seen_subcommand_from run" -l bundled-npm -d 'Forces npm to be the version bundled with Node'
complete -c volta -n "__fish_seen_subcommand_from run" -l no-yarn -d 'Disables Yarn'
complete -c volta -n "__fish_seen_subcommand_from run" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_seen_subcommand_from run" -s V -l version -d 'Prints version information'
complete -c volta -n "__fish_seen_subcommand_from run" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_seen_subcommand_from run" -l quiet -d 'Prevents unnecessary output'
complete -c volta -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c volta -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c volta -n "__fish_seen_subcommand_from help" -l verbose -d 'Enables verbose diagnostics'
complete -c volta -n "__fish_seen_subcommand_from help" -l quiet -d 'Prevents unnecessary output'
