#!/usr/bin/env sh

# Global Settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.98
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# General space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20

# Rules to allow dialogs to float.
yabai -m rule --add title='Preferences$' manage=off

