#!/usr/bin/env zsh

source "$HOME/.config/sketchybar/config.sh"

BG=0x2d2d3055

sketchybar --bar \
    height=33 \
    color=$TRANSPARENT \
    margin=0 \
		y_offset=2 \
    sticky=on \
		blur_radius=0 \
		position=top \
    padding_left=23 \
    padding_right=23 \
    notch_width=188 \
    display=main

# Alternative background colors
# label.color=0xffffffff
# background.color=0x9924273a
sketchybar --default \
    background.color=$BG \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Bold:15.0" \
    icon.padding_left=5 \
    icon.padding_right=6 \
    label.font="$FONT_FACE:Bold:12.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_right=5

source "$ITEMS_DIR/spaces.sh"

sketchybar --add item front_app left \
    --set front_app \
    background.color=$GREEN \
    background.padding_left=0 \
    background.padding_right=0 \
		icon.padding_left=7 \
    icon.y_offset=1 \
    icon.color=$BG \
    label.drawing=no \
    blur_radius=5 \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=$TRANSPARENT \
    background.padding_left=-3 \
    icon= \
    icon.color=$GREEN \
    icon.font="$FONT_FACE:Bold:20.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=$TRANSPARENT \
    background.padding_right=5 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:12.0" \
    label.drawing=yes

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
		icon.padding_left=10 \
		label.padding_right=10 \
    blur_radius=5 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item battery right \
    --set battery \
		icon.padding_left=10 \
		label.padding_right=10 \
		background.padding_left=5 \
    blur_radius=5 \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
