#!/usr/bin/env python3

import sys
from datetime import datetime

if len(sys.argv) < 2:
    sys.exit()

note_name = sys.argv[1]
if not note_name:
    sys.exit()

zid = datetime.now().strftime("%Y%m%d%H%M")
filename = "%s %s.md" % (zid, note_name)

with open(filename, "w") as file:
    file.write("")
    print(filename)
