#!/usr/bin/env bash

dst=$(printf '%s%s' unix: /tmp/kitty*)

# Spawn a new Kitty window.
/Applications/kitty.app/Contents/MacOS/kitty @ --to $dst new-window --window-type os

# Sends the command.
/Applications/kitty.app/Contents/MacOS/kitty @ --to $dst send-text "$1\n"

