#!/usr/bin/env node

const {execSync} = require('child_process')

const run = (...commands) =>
	execSync(commands.join(' ')).toString()

const log = (...texts) => console.log(...texts)

const getDevices = () =>
	JSON.parse(run('blueutil --paired --format json'))

const printDevices = () =>
	log(getDevices().map(device => device.name).join(' | '))

const printDevicesWithRSSI = () =>
	log(getDevices().map(device => `${device.name} (${device.rawRSSI})`).join('\n'))

printDevicesWithRSSI()


