#!/usr/bin/env python3

import os
import re
from datetime import datetime

def creation_time(path):
     s = os.stat(path)
     return s.st_birthtime

z_pattern = re.compile(r"$\d{12}")

for file in os.listdir():
    if file.endswith(".md"):
        created_at = creation_time(file)
        date = datetime.utcfromtimestamp(int(created_at)).strftime("%Y%m%d%H%M")

        if z_pattern.match(file):
            print("File %s is already prefixed correctly, pass." % file)
            continue

        new_file_name = "{} {}".format(date, file)

        os.rename(file, new_file_name)
        print("Renaming to %s" % new_file_name)

